version: '3.1'

services:
  app:
    image: 'gandalf:latest'
    build:
      context: .
    container_name: gandalf
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/gandalf
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  dbpostgresql:
    image: 'postgres'
    restart: unless-stopped
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gandalf
networks:
  default:
    external:
      name: challenge-network